// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utssmxappaywbvaxloxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0c3NteGFwcGF5d2J2YXhsb3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzYyMzgsImV4cCI6MjA3MjU1MjIzOH0.sOrjQ3ywLDEMcOg4dnBDZJL5gQPYXZrc09jE7G8VqXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});